/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MutationsRouteImport } from './routes/mutations'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MutationsRoute = MutationsRouteImport.update({
  id: '/mutations',
  path: '/mutations',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/design-system': typeof DesignSystemRoute
  '/inspector': typeof InspectorRoute
  '/memory': typeof MemoryRoute
  '/mutations': typeof MutationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/design-system': typeof DesignSystemRoute
  '/inspector': typeof InspectorRoute
  '/memory': typeof MemoryRoute
  '/mutations': typeof MutationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/design-system': typeof DesignSystemRoute
  '/inspector': typeof InspectorRoute
  '/memory': typeof MemoryRoute
  '/mutations': typeof MutationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/design-system'
    | '/inspector'
    | '/memory'
    | '/mutations'
    | '/search'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/design-system'
    | '/inspector'
    | '/memory'
    | '/mutations'
    | '/search'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/design-system'
    | '/inspector'
    | '/memory'
    | '/mutations'
    | '/search'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  DesignSystemRoute: typeof DesignSystemRoute
  InspectorRoute: typeof InspectorRoute
  MemoryRoute: typeof MemoryRoute
  MutationsRoute: typeof MutationsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutations': {
      id: '/mutations'
      path: '/mutations'
      fullPath: '/mutations'
      preLoaderRoute: typeof MutationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  DesignSystemRoute: DesignSystemRoute,
  InspectorRoute: InspectorRoute,
  MemoryRoute: MemoryRoute,
  MutationsRoute: MutationsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
